#Kane Compare

Comparing the data from ISCN with the data from the data re-ingest.

```{r warning=FALSE, message=FALSE}

datasetName <- "Kane" 

##### Extract the profile information ####
dataset_profile <- profile_raw  %>%
  filter(dataset_name_sub == datasetName) 

if(any(grepl('ISCN', dataset_profile$dataset_name_soc))){
  #reassign rows where the ISCN tried to fill in SOC values
  dataset_profile <- dataset_profile %>%
    group_by(dataset_name_soc) %>%
    mutate(`soc_depth (cm)` = if_else(grepl('ISCN', dataset_name_soc),
                                      rep(NA_character_, length(`soc_depth (cm)`)), `soc_depth (cm)`),
           `soc (g cm-2)` = if_else(grepl('ISCN', dataset_name_soc),
                                    rep(NA_character_, length(`soc (g cm-2)`)), `soc (g cm-2)`),
           soc_carbon_flag = if_else(grepl('ISCN', dataset_name_soc),
                                     rep(NA_character_, length(soc_carbon_flag)), soc_carbon_flag),
           soc_spatial_flag = if_else(grepl('ISCN', dataset_name_soc),
                                      rep(NA_character_, length(soc_spatial_flag)), soc_spatial_flag),
           soc_method = if_else(grepl('ISCN', dataset_name_soc), 
                                rep(NA_character_, length(soc_method)), soc_method)) %>%
    ungroup()
  
}

dataset_profile <- standardCast(dataset_profile)
```

```{r warning = FALSE, message = FALSE}
##### Extract the layer infromation ####

dataset_layer <- layer_raw %>%
  filter(dataset_name_sub == datasetName) 

if(any(grepl('ISCN', dataset_layer$dataset_name_soc))){
  #reassign rows where the ISCN tried to fill in SOC values
  dataset_layer <- dataset_layer %>%
    group_by(dataset_name_soc) %>%
    mutate(`soc (g cm-2)` = if_else(grepl('ISCN', dataset_name_soc),
                                    rep(NA_character_, length(`soc (g cm-2)`)), `soc (g cm-2)`),
           soc_carbon_flag = if_else(grepl('ISCN', dataset_name_soc),
                                     rep(NA_character_, length(soc_carbon_flag)), soc_carbon_flag),
           soc_method = if_else(grepl('ISCN', dataset_name_soc), 
                                rep(NA_character_, length(soc_method)), soc_method)) %>%
    ungroup()
  
}

#remove the soc dataset since we've taken care of the ISCN notation
dataset_layer <- select(dataset_layer, -dataset_name_soc) 

if(any(count(dataset_layer, dataset_name_sub, site_name, profile_name, layer_name)$n > 1)){
  #if the rows are duplicated then fill in missing values by group
  dataset_layer <- dataset_layer %>%
    group_by(dataset_name_sub, site_name, profile_name, layer_name) %>%
    mutate_at(vars(-group_cols()), 
              function(xx){ifelse(sum(!is.na(xx)) == 1, rep(xx[!is.na(xx)], length(xx)),xx)}) %>% #if there is one value that isn't na then populate the rest of the entry, this fills in the
    ungroup() %>%
    unique() #collapase rows that are non-unique
}

dataset_layer <- standardCast(dataset_layer)

```

```{r reingest}

#load in the data from reingest for comparing
data_reingest <- readKane2004('~/Desktop/Research/data_reingests/Kane')

```

``` {r editReingest}

# #the data reingest untouched
# soilProfile <- data_reingest$x190_2031_all_soil_profile_depths_carbon_BD.txt
#   
# #checking to see if as.numeric adds NA values
# compareReingest <- data_reingest$x190_2031_all_soil_profile_depths_carbon_BD.txt %>%
#   mutate(across(c("Oe+Oa_%C", "A_%C", "B1_%C", "A_BD"), as.numeric))

editReingest <- data_reingest$x190_2031_all_soil_profile_depths_carbon_BD.txt %>%
  pivot_longer(cols = c("Oi_depth", "Oe+Oa_depth", "A_depth", "B1_depth", "Oi_%C", "Oe+Oa_%C", "A_%C", "B1_%C", "Oi_BD", "Oe+Oa_BD", "A_BD", "B1_BD"), #pivot longer using everything that is not an identifier
               names_to = "header") %>%
  separate(col = header, #use the separate function to separate the horizons and variable types
           into = c("hzn_desgn", "variable_type"),
           sep = "_") %>%
  pivot_wider(names_from = c("variable_type"), #pivot wider to resemble the dataset_layer
              values_from = "value") %>%
  rename("c_tot (percent)" = "%C") %>%
  #rename("layer_bot (cm)" = "depth") %>%
  na_if("nd") %>%
  mutate(hzn = substr(hzn_desgn, 1, 1)) %>%
  mutate(site_shortened = substr(site, 1, 1)) %>%
  mutate(profile_name = sprintf("% s% s,%s,%s", site_shortened, productivity_level, replicate, pit)) #%>%
  #mutate(layer_name = sprintf("% s_% s", profile_name, `layer_bot (cm)`))
  #rename("bd_tot (g cm-3)" = "BD") #don't use this line yet, not confident on BD unit


#code to create a top and bottom layer

```

```{r histograms}

ggplot(editReingest) +
  geom_histogram(mapping = aes(x = as.numeric(BD)), fill = 'orange') +
  geom_histogram(data = dataset_layer,
                 mapping = aes(x = `bd_tot (g cm-3)`), fill = 'blue', alpha = .5)

```