---
title: "Dev new process"
author: "K Todd-Brown (ktoddbrown@gmail.com)"
date: "8/22/2019"
output: html_document
---

```{r setup}
library(data.table)

tableOrder <- c('site', 'plot', 'layer')
```

```{r readTest01}
test01.ls <- list( dataTable1 = data.table::fread(input = '../temp/testCase/Test01_dataTable1-Table 1.csv')[,1:2], 
dataTable2 = data.table::fread(input = '../temp/testCase/Test01_dataTable2-Table 1.csv')[,1:6],
key = data.table::fread(input='../temp/testCase/Test01_key-Table 1.csv', header=TRUE)[,1:5])

test02.ls <- list(dataTable = data.table::fread(input='../temp/testCase/Test02_dataTable-Table 1.csv'),
                  key = data.table::fread(input = '../temp/testCase/TestKey02-Table 1.csv', header = TRUE)[, 1:5])

targetKey <- data.table::fread(input = '../temp/testCase/TargetKey-Table 1.csv', header = TRUE)[,1:3]
```

```{r dataIn}

sourceData.ls <- test01.ls
key <- merge(targetKey[,c('table', 'variable')], 
             sourceData.ls$key[,c('table', 'header', 'entry', 'type', 'variable')],
             by=c('variable'), suffixes = c('_target', '_source'),
             all=TRUE)

##check for dropped data columns
danglingHeader <- key[is.na(header) & is.na(table_target)]
if(nrow(danglingHeader) > 0){
  warning(paste('Dangling columns in source file that will be dropped:', paste( danglingHeader$header, collapse = ' ')))
}

missingHeader <- key[is.na(header) & !is.na(table_target)]
if(nrow(missingHeader) > 0){
  warning(paste('Missing source header connectin to target table:',
                paste(missingHeader$variable, collapse = ' ')))
}

key <- key[!is.na(header) & !is.na(table_target)]

ans <- list()
for(targetTbl in c(tableOrder, base::setdiff(unique(key$table_target), tableOrder))) {
  if(!(targetTbl %in% key$table_target)){
    next()
  }
  
  ans[[targetTbl]] <- data.table()
  orderSource <- sort(table(key[table_target == targetTbl]$table_source))
  for(sourceTbl in names(orderSource)){
    #pull the relvant table
    xx <- key[table_source == sourceTbl & table_target == targetTbl]
    
    if(nrow(xx) == 0){
      next()
    }
    
    #Pull all the columns indicated by the key
    columnNames <- (xx[xx$header != '',])$header
    sourcedata <- (sourceData.ls[[sourceTbl]])[,..columnNames]
  
    ##rename headers => variable_type
    data.table::setnames(sourcedata, 
                         (xx[xx$header != '',])$header,
                         paste0((xx[xx$header != '',])$variable, '_',
                                (xx[xx$header != '',])$type))
    #print(sourcedata)
    
    ##keep track of any basic patters (ie key$type) 
    ##...that will need to be converted to long format at the end
    meltPatternStr <- c()
        
    ##add any hard coded information from the key (generally units or methods)
    hardEntry <- xx[xx$header == '',]

    if(nrow(hardEntry) > 0){
       sourcedata <- cbind(sourcedata, 
                        #set the hard entries
                        as.data.frame(stats::setNames(as.list(hardEntry$entry),
                                              paste0(hardEntry$variable, '_', hardEntry$type))))
       meltPatternStr <- unique(c(hardEntry$type), meltPatternStr)
    }
    
    ##add any entries from the source data tables
    softEntry <- xx[xx$header != '' & xx$type != 'id',]
    if(nrow(softEntry) > 0){
      sourcedata <- cbind(sourcedata, 
                        #preserve the variable names
                        as.data.frame(stats::setNames(as.list(unique(softEntry$variable)),
                                                      paste0(unique(softEntry$variable), '_name'))))
      meltPatternStr <- unique(c(softEntry$type, 'name', meltPatternStr))
    }
    
    ##Transform data from wide format to long format
    if(length(meltPatternStr) > 0){
      #make sure every variable has all the types filled in so things melt properly
      possibleHeaders <- expand.grid(unique(c(softEntry$variable, hardEntry$variable)), meltPatternStr)
      possibleHeaders$header <- sprintf('%s_%s', possibleHeaders[,1], possibleHeaders[,2])
      
      if(any(!(possibleHeaders$header %in% names(sourcedata)))){
        missingHeaders <- as.data.frame(stats::setNames(as.list(rep(NA, nrow(possibleHeaders))), possibleHeaders$header))
        missingHeaders <- missingHeaders[!(names(missingHeaders) %in% names(sourcedata))]
        sourcedata <- cbind(sourcedata, missingHeaders[,!(names(missingHeaders) %in% names(sourcedata))])
      }
      
      #make sure ordering is correct so the melt gets orders right
      setcolorder(sourcedata, neworder = sort(names(sourcedata)))
      
      #and use the data table fancy melt
      sourcedata <- melt(sourcedata,
                     measure=patterns(paste0('_', meltPatternStr, '$')), 
         value.name = meltPatternStr)[,-'variable']
    }
    
    ##merge it with the data from other tables
    if(nrow(ans[[targetTbl]]) == 0){
      ans[[targetTbl]] <- sourcedata
    }else{
      ans[[targetTbl]] <- merge(ans[[targetTbl]], sourcedata)
    }
  }
}
```

```{r old eval=FALSE}
#make new name that we can parse easily
key[,newName := paste0(variable, '_', type)]

renameHeaders <- unique(key[header_source != ''][,c('header_source', 'newName')])

testing <- copy(key)
testing2 <- testing[, .(dataset = .(test01.ls[[table_source]])), 
                    by=.(table_target, table_source)]


testing3 <- testing[, list(dataset = list({
  print(paste('--', table_source, '--'))
  ##pull the data from the source table
  sourceData <- test01.ls[[table_source]]
  #headerNames <- header_source[header_source != '']
  ##print(headerNames)
  #print(sourceData)
  #sourceData <- sourceData[..headerNames]
  #print(sourceData)
  ##rename columns
  sourceData <- sourceData[,setnames(.SD, renameHeaders$header_source, renameHeaders$newName, skip_absent = TRUE)];
  ##pull variable names to presever
  softEntry <- as.list(unique(variable[header_source != '' & type != 'id']));
  hardEntry <- as.list(unique(variable[header_source == '']));
  
  if(length(softEntry) > 0){
  varNames <- as.data.frame(stats::setNames(softEntry, paste0(softEntry, '_name')));
  
  ##set the hard entries
  sourceData <- cbind(sourceData, 
                        #set the hard entries
                        as.data.frame(stats::setNames(as.list(entry[header_source == '']), paste0(variable[header_source == ''], '_', type[header_source == '']))), 
                        #preserve the variable names
                        varNames)
  
  #print(sourceData)
  #print(paste0('_', setdiff(unique(type), 'id'), '$'))
  sourceData <- melt(sourceData, 
                     measure=patterns(paste0('_', c('name', setdiff(unique(type), 'id')), '$')), 
         value.name = unlist(c('name', setdiff(unique(type), 'id'))))[,-'variable']
  }
  
  sourceData})), 
                    by=.(table_source, table_target)]

testing4 <- testing3[, list(data = list(rbindlist(dataset, fill=TRUE))), by=.(table_target)]

temp[[1]][, setnames(.SD, renameHeaders$header_source, renameHeaders$newName, skip_absent = TRUE)]

dt <- data.table(x=1:5)[,list(y=letters[1:x],z=sample(1:100,x)),by=x]
dt2 <- dt[, list(dt.yz=list(data.table(y, z))), by=x]

ans <- plyr::dlply(as.data.frame(key), c('table_target'), function(xx){
  print(paste('Going to:', xx$table_target[1]))
  #xx <- as.data.frame(key[table_target == 'site'])
  #yy <- as.data.frame(key[table_target == 'site' & table_source == 'dataTable1'])
  temp <- plyr::dlply(xx, c('table_source'), function(yy){
    print(paste('from', yy$table_source[1]))
    #print(class(yy))
    
    hardEntry <- yy[yy$header_source == '',]
    softEntry <- yy[yy$header_source != '' & yy$type != 'id',]
    #print(yy$table_source[1])
    columnNames <- (yy[yy$header_source != '',])$header_source
    
    if(sum(softEntry$type != 'id') == 0){
      return(NULL)
    }
    #print(columnNames)
    
    sourcedata <- (test01.ls[[yy$table_source[1]]])[,..columnNames]
    #print(sourcedata)
    
    ##rename headers => variable_type
    data.table::setnames(sourcedata, (yy[yy$header_source != '',])$header_source,
                         (yy[yy$header_source != '',])$newName)
    #print(sourcedata)
    
    ##set the hard entries
    sourcedata <- cbind(sourcedata, 
                        #set the hard entries
                        as.data.frame(stats::setNames(as.list(hardEntry$entry), hardEntry$newName)), 
                        #preserve the variable names
                        as.data.frame(stats::setNames(as.list(softEntry$variable), paste0(softEntry$variable, '_name'))))
    
    #print('***')
    #print(sourcedata)
    
    ##melt magic
    ans <- melt(sourcedata, measure=patterns(paste0('_', unique(setdiff(c('name', yy$type), 'id')), '$')), 
         value.name = unique(setdiff(c('name', yy$type), 'id')))[,-'variable']
    
    return(unique(ans))
  })
  return(rbindlist(temp, fill=TRUE))
})
```