---
title: "FIA data merge"
author: "Kathe Todd-Brown, Ursa"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(readr)
library(googlesheets4)
library(SOCDRaH2)

```

```{r downloadData}

##Download ISCN and FIA tables (layer, profile, citation, dataset and Soils_Lab, Soils_Sample_Location)

#download from edi
ISCN_layer_old.df <- read_delim(file = "https://portal.edirepository.org/nis/dataviewer?packageid=edi.1160.1&entityid=4af719a84f8981fcc63f1f92760cb253",
                    col_types = cols(.default =col_character()),
                    delim = ';',
                    n_max = 1e6)

#download using read script to fix errors
ISCN.ls <- ISCN3_3(data_dir = '~/Documents/datasets/ISCN')

ISCN_layer.df <- ISCN.ls$layer
ISCN_profile.df <- ISCN.ls$profile

# #ISCN_profile.df <- read_delim(file = 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.1160.1&entityid=40527580cc045d33d9a5aaf728bf204e',
#                     col_types = cols(.default =col_character()),
#                     delim = ';',
#                     n_max = 1e5)

ISCN_citation.df <- read_delim(file = 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.1160.1&entityid=320e31ca911f187550ca2143c31fd408',
                    col_types = cols(.default =col_character()),
                    delim = ';',
                    n_max = 1e5)

ISCN_dataset.df <- read_delim(file = 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.1160.1&entityid=cdd0c7a4cac3f28d6d788c91f506775f',
                    col_types = cols(.default =col_character()),
                    delim = ';',
                    n_max = 1e5)


FIA_lab.df <- read_delim("~/Desktop/Datasets/ENTIRE_SOILS_LAB.csv", col_types = cols(.default =col_character()),
                    delim = ',',
                    n_max = 1e5)

FIA_loc.df <- read_delim("~/Desktop/Datasets/ENTIRE_SOILS_SAMPLE_LOC.csv", col_types = cols(.default =col_character()),
                    delim = ',',
                    n_max = 1e5)

# add ENTIRE_SURVEY.CSV and ENTIRE_PLOT.CSV from the fiadb
# documentation available on the user guide [provide page number and citation for future reference]

  
```


```{r}
#Concatenate citations for same datasets
ISCN_citation.df <- ISCN_citation.df %>% 
  group_by(dataset_name) %>% 
  mutate(citation = paste0(citation, collapse = "; ")) %>%
  distinct(dataset_name, .keep_all = TRUE)


#try to fix duplicate layer names in northern circumpolar dataset
ISCN3_layer.df <- ISCN3_layer.df %>% mutate(layer_name = if_else(dataset_name_sub == "Northern Circumpolar Soil Carbon Database (NCSCD)" & grepl("^200", layer_name), paste(gsub("\\.\\d+$", "", layer_name), `layer_bot (cm)`, sep = "."), layer_name))

northern <- ISCN_layer.df$layer_name[ISCN_layer.df$dataset_name_sub == "Northern Circumpolar Soil Carbon Database (NCSCD)" & ISCN_layer.df$dataset_name_soc == "ISCN No SOC stock computation" & grepl("^200", ISCN_layer.df$layer_name)]

northern2 <- ISCN_layer.df$layer_name[ISCN_layer.df$dataset_name_sub == "Northern Circumpolar Soil Carbon Database (NCSCD)" & ISCN_layer.df$dataset_name_soc == "Northern Circumpolar Soil Carbon Database (NCSCD)" & grepl("^200", ISCN_layer.df$layer_name)]

#give each row a unique id if still duplicates
ISCN_layer.df <- ISCN_layer.df %>% distinct() %>% mutate(observation_id = row_number())

```

```{r}

#find duplicate samples in layer table
ISCN_layer.df <- ISCN_layer.df %>%
  group_by(dataset_name_sub, site_name, profile_name, layer_name, `layer_top (cm)`, `layer_bot (cm)`) %>%
  mutate(id = cur_group_id()) %>%
  ungroup()

ISCN_duplicated.df <- ISCN_layer.df[duplicated(ISCN_layer.df$id), ]

all_duplicates <- ISCN_layer.df %>% filter(id %in% ISCN_duplicated.df$id)

unique(all_duplicates$dataset_name_sub)

NRCS_dup <- all_duplicates %>% subset(dataset_name_sub == 'NRCS Sept/2014')
worldwide_dup <- all_duplicates %>% subset(dataset_name_sub == 'Worldwide soil carbon and nitrogen data')
northern_dup <- all_duplicates %>% subset(dataset_name_sub == 'Northern Circumpolar Soil Carbon Database (NCSCD)')
UMBS_dup <- all_duplicates %>% subset(dataset_name_sub == 'UMBS_FASET') %>% distinct()

```

```{r}
#Create long table of each FIA dataset

#retrieve FIA annotations from datakeys sheet
FIA_lab.dataAnnotation <- read_sheet("https://docs.google.com/spreadsheets/d/1mllMhm2V2kMv6KvPSnuXDEBWAS-2okWK2F4mXbSjphU/edit?usp=sharing", sheet = "dataAnnotation", range = "dataAnnotation!A:F") %>% filter(study_id == 'FIADB_RMRS') %>% filter(table_id == "Soils_Lab")


FIA_lab_long.df <- FIA_lab.df %>%
  mutate(study_id = 'FIADB_RMRS', 
         table_id = 'Soils_Lab')  %>%
  #Group by the columns that are identifiers
  group_by(across(all_of((FIA_lab.dataAnnotation %>%
                           filter(is_type == 'identifier'))$column_id))) %>%
  #Pull the current group index or id 
  mutate(observation_id = cur_group_id()) %>%
  #and then remove the grouping so we can move on
  ungroup() %>%
  pivot_longer(cols = -c(study_id, table_id, observation_id), names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  full_join(FIA_lab.dataAnnotation, 
            by = join_by(study_id, table_id, column_id),
            suffix = c('.data', ''), multiple = 'all') %>%
  mutate(
    with_entry = if_else((with_entry == "--") | is.na(with_entry), with_entry.data, with_entry)) %>%
  select(-with_entry.data)


FIA_loc.dataAnnotation <- read_sheet("https://docs.google.com/spreadsheets/d/1mllMhm2V2kMv6KvPSnuXDEBWAS-2okWK2F4mXbSjphU/edit?usp=sharing", sheet = "dataAnnotation", range = "dataAnnotation!A:F") %>% filter(study_id == 'FIADB_RMRS') %>% filter(table_id == "Soils_Sample_Location")

FIA_loc_long.df <- FIA_loc.df %>%
  #add the study and table id manually
  mutate(study_id = 'FIADB_RMRS', 
         table_id = 'Soils_Sample_Location') %>%
  #Group by the columns that are identifiers
  group_by(across(all_of((FIA_loc.dataAnnotation %>%
                           filter(is_type == 'identifier'))$column_id))) %>%
  #Pull the current group index or id 
  mutate(observation_id = cur_group_id()) %>%
  #and then remove the grouping so we can move on
  ungroup() %>%
  #shoe string the data
  pivot_longer(cols = -c(study_id, table_id, observation_id),
               names_to = 'column_id', 
               values_to = 'with_entry',
               values_drop_na = TRUE) %>%
  #annotate so that we can also have the 'meta' data
  full_join(FIA_loc.dataAnnotation, 
            by = join_by(study_id, table_id, column_id),
            suffix = c('.data', ''),
            multiple = 'all') %>%
  #deal with entries from both the meta and data tables
  mutate(
    with_entry = if_else((with_entry == "--") | is.na(with_entry), with_entry.data, with_entry)) %>%
  select(-with_entry.data)

```

```{r}
#Create long table of each ISCN dataset

#retrieve ISCN annotations from datakeys sheet
ISCN_layer.dataAnnotation <- read_sheet("https://docs.google.com/spreadsheets/d/1mllMhm2V2kMv6KvPSnuXDEBWAS-2okWK2F4mXbSjphU/edit?usp=sharing", sheet = "dataAnnotation", range = "dataAnnotation!A:F") %>% filter(study_id == 'ISCN3') %>% filter(table_id == "layer")

ISCN_layer_long.df <- ISCN_layer.df %>%
  #convert all columns to characters
  mutate(across(everything(), as.character)) %>%
  mutate(study_id = 'ISCN3', 
         table_id = 'layer')  %>%
  #Group by the columns that are identifiers
  group_by(across(all_of((ISCN_layer.dataAnnotation %>%
                           filter(is_type == 'identifier'))$column_id))) %>%
  #Pull the current group index or id 
  mutate(observation_id = cur_group_id()) %>%
  #and then remove the grouping so we can move on
  ungroup() %>%
  pivot_longer(cols = -c(study_id, table_id, observation_id), names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  full_join(ISCN_layer.dataAnnotation, 
            by = join_by(study_id, table_id, column_id),
            suffix = c('.data', ''), multiple = 'all') %>%
  mutate(
    with_entry = if_else((with_entry == "--") | is.na(with_entry), with_entry.data, with_entry)) %>%
  select(-with_entry.data)


#retrieve ISCN annotations from datakeys sheet
ISCN_profile.dataAnnotation <- read_sheet("https://docs.google.com/spreadsheets/d/1mllMhm2V2kMv6KvPSnuXDEBWAS-2okWK2F4mXbSjphU/edit?usp=sharing", sheet = "dataAnnotation", range = "dataAnnotation!A:F") %>% filter(study_id == 'ISCN3') %>% filter(table_id == "profile")

ISCN_profile_long.df <- ISCN_profile.df %>%
  mutate(study_id = 'ISCN3', 
         table_id = 'profile')  %>%
  #Group by the columns that are identifiers
  group_by(across(all_of((ISCN_profile.dataAnnotation %>%
                           filter(is_type == 'identifier'))$column_id))) %>%
  #Pull the current group index or id 
  mutate(observation_id = cur_group_id()) %>%
  #and then remove the grouping so we can move on
  ungroup() %>%
  pivot_longer(cols = -c(study_id, table_id, observation_id), names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  full_join(ISCN_profile.dataAnnotation, 
            by = join_by(study_id, table_id, column_id),
            suffix = c('.data', ''), multiple = 'all') %>%
  mutate(
    with_entry = if_else((with_entry == "--") | is.na(with_entry), with_entry.data, with_entry)) %>%
  select(-with_entry.data)


#retrieve ISCN annotations from datakeys sheet
ISCN_citation.dataAnnotation <- read_sheet("https://docs.google.com/spreadsheets/d/1mllMhm2V2kMv6KvPSnuXDEBWAS-2okWK2F4mXbSjphU/edit?usp=sharing", sheet = "dataAnnotation", range = "dataAnnotation!A:F") %>% filter(study_id == 'ISCN3') %>% filter(table_id == "citation")

ISCN_citation_long.df <- ISCN_citation.df %>%
  mutate(study_id = 'ISCN3', 
         table_id = 'citation')  %>%
  #Group by the columns that are identifiers
  group_by(across(all_of((ISCN_citation.dataAnnotation %>%
                           filter(is_type == 'identifier'))$column_id))) %>%
  #Pull the current group index or id 
  mutate(observation_id = cur_group_id()) %>%
  #and then remove the grouping so we can move on
  ungroup() %>%
  pivot_longer(cols = -c(study_id, table_id, observation_id), names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  full_join(ISCN_citation.dataAnnotation, 
            by = join_by(study_id, table_id, column_id),
            suffix = c('.data', ''), multiple = 'all') %>%
  mutate(
    with_entry = if_else((with_entry == "--") | is.na(with_entry), with_entry.data, with_entry)) %>%
  select(-with_entry.data)
   
#retrieve ISCN annotations from datakeys sheet
ISCN_dataset.dataAnnotation <- read_sheet("https://docs.google.com/spreadsheets/d/1mllMhm2V2kMv6KvPSnuXDEBWAS-2okWK2F4mXbSjphU/edit?usp=sharing", sheet = "dataAnnotation", range = "dataAnnotation!A:F") %>% filter(study_id == 'ISCN3') %>% filter(table_id == "dataset")

ISCN_dataset_long.df <- ISCN_dataset.df %>%
  mutate(study_id = 'ISCN3', 
         table_id = 'dataset')  %>%
  #Group by the columns that are identifiers
  group_by(across(all_of((ISCN_dataset.dataAnnotation %>%
                           filter(is_type == 'identifier'))$column_id))) %>%
  #Pull the current group index or id 
  mutate(observation_id = cur_group_id()) %>%
  #and then remove the grouping so we can move on
  ungroup() %>%
  pivot_longer(cols = -c(study_id, table_id, observation_id), names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  full_join(ISCN_dataset.dataAnnotation, 
            by = join_by(study_id, table_id, column_id),
            suffix = c('.data', ''), multiple = 'all') %>%
  mutate(
    with_entry = if_else((with_entry == "--") | is.na(with_entry), with_entry.data, with_entry)) %>%
  select(-with_entry.data)
   
```


# Pulling things together

```{r}
#Bind all long tables together

bigData <- FIA_loc_long.df %>%
  select(study_id, table_id, observation_id, of_variable, is_type, with_entry) %>%
  bind_rows(FIA_lab_long.df %>%
              select(study_id, table_id, observation_id, of_variable, is_type, with_entry)) %>%
  bind_rows(ISCN_layer_long.df %>%
              select(study_id, table_id, observation_id, of_variable, is_type, with_entry)) %>%
  bind_rows(ISCN_profile_long.df %>%
              select(study_id, table_id, observation_id, of_variable, is_type, with_entry)) %>%
  bind_rows(ISCN_citation_long.df %>%
              select(study_id, table_id, observation_id, of_variable, is_type, with_entry)) %>%
  bind_rows(ISCN_dataset_long.df %>%
              select(study_id, table_id, observation_id, of_variable, is_type, with_entry)) #%>%
  #unique() #remove duplicates from repeated methods applying to multiple columns
```

# Annotations harmonization

```{r}
#retrieve variable map
variableMap <- read_sheet("https://docs.google.com/spreadsheets/d/1mllMhm2V2kMv6KvPSnuXDEBWAS-2okWK2F4mXbSjphU/edit?usp=sharing", sheet = "variableMap", range = "variableMap!A:D")

#rename variables based on map
newData.df <- bigData %>%
  left_join(variableMap, by = join_by(study_id, table_id, of_variable)) %>%
  select(-of_variable) %>%
  rename(of_variable = ISCN3_target_variable)

#remove entries with no variable specified
newData.df <- newData.df[!grepl('--|NA', newData.df$of_variable),]

#newData.df <- newData.df[!duplicated(newData.df[ , c("study_id","table_id", "observation_id", "is_type", "of_variable")]),]
  
```

# Plot it

```{r}
#pivot out data
data_wide_values.df <- newData.df %>%
  filter(is_type %in% c('value', 'identifier')) %>%
  select(-is_type) %>%
  pivot_wider(names_from=of_variable, 
              values_from=with_entry,
              values_fn = function(xx) {return(xx[1])}) #hack to make pivot work

data_wide_values.df <- data_wide_values.df %>%
  mutate(across(.cols = starts_with('bulk_density'), as.numeric))

ggplot(data_wide_values.df) +
  geom_histogram(aes(x=bulk_density_whole_soil)) +
  facet_wrap(~study_id, scales='free_y') +
  scale_x_log10() +
  scale_y_log10()
ggplot(data_wide_values.df %>%
         pivot_longer(cols = c(bulk_density_whole_soil, bulk_density_fine_earth, bulk_density_unknown))) +
  geom_histogram(aes(x=value, fill = study_id)) +
  facet_grid(study_id~name, scales = 'free_y') +
  scale_x_log10() +
  scale_y_log10()

```


#Test comparing raw data to combined by plots (organic carbon)
```{r}
data_wide_values.df <- data_wide_values.df %>%
  mutate(across(.cols = starts_with('organic_carbon'), as.numeric))

ggplot(data_wide_values.df) +
  geom_histogram(aes(x=organic_carbon, fill = study_id)) +
  facet_wrap(~study_id, scales='free_y') #+
  #scale_x_log10() +
  #scale_y_log10()


ISCN_layer.df <- ISCN_layer.df %>% mutate(`oc (percent)` = as.numeric(`oc (percent)`))

ggplot(ISCN_layer.df) +
  geom_histogram(aes(x=`oc (percent)`), fill = "#00BFC4") #+
  #facet_wrap(scales='free_y') +
  #scale_x_log10() +
  #scale_y_log10()

FIA_lab.df <- FIA_lab.df %>% mutate(C_ORG_PCT = as.numeric(C_ORG_PCT))

ggplot(FIA_lab.df) +
  geom_histogram(aes(x=C_ORG_PCT), fill = "#F8766D") #+
  #facet_wrap(scales='free_y') +
  #scale_x_log10() +
  #scale_y_log10()


```

#Tests comparing raw data to combined by exact values (organic carbon in layer and soil lab)
```{r}
data_wide_values.df <- data_wide_values.df %>%
  mutate(across(.cols = starts_with('organic_carbon'), as.numeric))

organic_carbon_ISCN <- ISCN_layer.df$`oc (percent)`

organic_carbon_ISCN_merged <- data_wide_values.df %>% filter(table_id == "layer") %>% filter(row_number() <= n()-1)

organic_carbon_ISCN_merged <- organic_carbon_ISCN_merged$organic_carbon

identical(organic_carbon_ISCN, organic_carbon_ISCN_merged)



organic_carbon_FIA <- FIA_lab.df$C_ORG_PCT

organic_carbon_FIA <- as.numeric(organic_carbon_FIA)

organic_carbon_FIA <- organic_carbon_FIA[!is.na(organic_carbon_FIA)]

organic_carbon_FIA_merged <- data_wide_values.df %>% filter(table_id == "Soils_Lab")

organic_carbon_FIA_merged <- organic_carbon_FIA_merged$organic_carbon

organic_carbon_FIA_merged <- organic_carbon_FIA_merged[!is.na(organic_carbon_FIA_merged)]

identical(organic_carbon_FIA, organic_carbon_FIA_merged)

```
#Tests comparing raw data to combined by exact values (profile, citation, dataset)
```{r}
data_wide_values.df %>% 
  drop_na(-c("study_id", "table_id"))

landform_ISCN <- ISCN_profile.df$`landform (landform)`

landform_ISCN_merged <- data_wide_values.df %>% filter(table_id == "profile") %>% filter(row_number() <= n()-1)

landform_ISCN_merged <- landform_ISCN_merged$landform

identical(landform_ISCN, landform_ISCN_merged)



citation_ISCN <- ISCN_citation.df$citation

citation_ISCN_merged <- data_wide_values.df %>% filter(table_id == "citation")

citation_ISCN_merged <- citation_ISCN_merged$citation

identical(citation_ISCN, citation_ISCN_merged)



curator_name_ISCN <- ISCN_dataset.df$curator_name

curator_name_ISCN_merged <- data_wide_values.df %>% filter(table_id == "dataset")

curator_name_ISCN_merged <- curator_name_ISCN_merged$curator_name

identical(curator_name_ISCN, curator_name_ISCN_merged)

```