---
title: "Example of merging data files"
author: "Kathe Todd-Brown <ktoddbrown@ufl.edu>"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
---

```{r setup}
library(tidyverse)

```

```{r downloadData}
#download and simplify the files to only look at bulk density

#ISCN3Datafile <- '~/Documents/Datasets/ISCN_new/ISCN3_layer.csv'
ISCN.df <- read_delim(file = 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.1160.1&entityid=4af719a84f8981fcc63f1f92760cb253',
                    col_types = cols(.default =col_character()),
                    delim = ';',
                    n_max = Inf)  %>%
  select("dataset_name_sub", "site_name", "profile_name", "layer_name", #ID columns
         "bd_method", "bd_samp (g cm-3)", "bd_tot (g cm-3)", "bd_whole (g cm-3)", "bd_other (g cm-3)", "bdNRCS_prep_code")# bulk density columns

#Download url
#co_soils_visit <- read.csv('https://apps.fs.usda.gov/fia/datamart/CSV/CO_SOILS_VISIT.csv')
#co_soils_lab <- read.csv('https://apps.fs.usda.gov/fia/datamart/CSV/CO_SOILS_LAB.csv')

FIA.df <- read_csv(file = 'https://apps.fs.usda.gov/fia/datamart/CSV/CO_SOILS_LAB.csv',
                    col_types = cols(.default =col_character())) %>%
  select("CN", "STATECD", "COUNTYCD", "PLOT", "SMPLNNBR", "VSTNBR", "LAYER_TYPE", #ID columns
         "BULK_DENSITY") # bulk density columns
```

# Method 1: no metadata

Assign everything in line via scripts and use the code as documentation.

```{r eval=FALSE}
##RESCUE OLD CODE Do not refer to the dataStructure nor dataDescriptions here
#Transform the data into a set of id-variable-value-unit-method 


data1.df <- FIA.df %>%
  mutate(study_id = 'FIADB_RMRS', table_id = 'Soils_Lab') %>%
  #pivot the values longer
  pivot_longer(cols = valueCols$column_id, names_to = 'column_id', 
               values_to = 'value', values_drop_na = TRUE) %>%
  left_join(FIA.dataDescription, by = join_by(study_id, table_id, column_id))%>%
  mutate(variable = 'bulk_density')
  


ISCN.dataDescription <- ISCN.dataDescription %>%
  pivot_wider(names_from = is_type, values_from=with_entry)

valueRows <- ISCN.dataStructure %>%
  filter(is_type %in% c('value'))

temp2 <- ISCN.dataStructure %>%
              full_join(ISCN.dataDescription)


##CODE BELOW HERE BROKEN##
#Need to figure out how to assign all the units/methods from
#...the dataDescription to each colume and then 
#...link everything up with the variables in dataStructure
temp1 <- ISCN.df %>%
  mutate(study_id = 'ISCN3', table_id = 'layer') %>%
  pivot_longer(cols = ISCN.dataStructure$column_id,
               names_to = 'column_id',
               values_to = 'with_entry',
               values_drop_na = TRUE) %>%
  left_join(ISCN.dataStructure %>%
              full_join(ISCN.dataDescription)) %>%
  select(-column_id) %>%
  pivot_wider(names_from = is_type,
              values_from = with_entry,
              values_fn = list) %>%
  left_join(ISCN.dataDescription) 
  
  
  left_join(ISCN.dataDescription, by = c('study_id', 'table_id', 'column_id')) %>%
  mutate(method = paste0('bdNRCS_prep_code:', bdNRCS_prep_code, "; ", 
                         'bd_method:', bd_method,  "; ", 
                         'metadata_method:', method)) %>%
  select(-c('bd_method', 'bdNRCS_prep_code', 'control_vocabulary')) %>%
  mutate(variable = 'bulk_density')
  
dataFull.df <- data1.df %>%
  bind_rows(data2.df)

```

# Method 2

Leveraging meta data annotions more generally to document tranformations.

```{r}

#Transform the data into a set of id-variable-value-unit-method 

FIA.dataStructure <- tribble(~'study_id', ~'table_id', ~'column_id', ~'is_type', ~of_variable,
  'FIADB_RMRS', 'Soils_Lab', 'BULK_DENSITY', 'value', 'Bulk_density'
)

FIA.dataDescription <- tribble(~'study_id', ~'table_id', ~'column_id', ~'is_type', ~'with_entry',
         'FIADB_RMRS', 'Soils_Lab',	'BULK_DENSITY', 'unit', 'g cm^-3',
'FIADB_RMRS','Soils_Lab', 'BULK_DENSITY', 'method','mass per volume of oven-dry soil inclusive of coarse fraction') 


FIA_long.df <- FIA.df %>%
  mutate(study_id = 'FIADB_RMRS', table_id = 'Soils_Lab') %>%
  #pivot the values longer
  pivot_longer(cols = FIA.dataStructure$column_id, names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  left_join(FIA.dataStructure, by = join_by(study_id, table_id, column_id)) %>%
  pivot_wider(names_from = is_type, values_from = with_entry) %>%
  left_join(FIA.dataDescription %>%
              pivot_wider(names_from = 'is_type', values_from = 'with_entry'), 
            by = join_by(study_id, table_id, column_id))
  
```

```{r}
ISCN.dataDescription <- tribble(~'study_id', ~'table_id', ~'column_id',~'is_type', ~'with_entry',
'ISCN3',	'layer',	'bd_method',	'description',	"Method used to determine bulk density",
'ISCN3',	'layer',	'bd_samp (g cm-3)',	'description',	'Grams of oven-dried soil per cubic centimeter, with soil particles greater than 2 mm and roots greater that 1 cm diameter removed',
'ISCN3',	'layer',	'bd_samp (g cm-3)',	'unit',	'g cm-3',
'ISCN3',	'layer',	'bd_samp (g cm-3)',	'method',	'Fine earth bulk density',
'ISCN3',	'layer',	'bd_tot (g cm-3)',	'description',	'Grams of oven-dried soil per cubic centimeter, with soil particles greater than 2 mm and roots greater that 1 cm diameter included',
'ISCN3',	'layer',	'bd_tot (g cm-3)',	'unit',	'g cm-3',
'ISCN3',	'layer',	'bd_tot (g cm-3)',	'method',	'Whole soil bulk density',
'ISCN3',	'layer',	'bd_whole (g cm-3)',	'description',	'Grams of oven-dried soil per cubic centimeter, with the content of soil particles >2mm and roots >1cm diameter estimated and subtracted',
'ISCN3',	'layer',	'bd_whole (g cm-3)',	'unit',	'g cm-3',
'ISCN3',	'layer',	'bd_whole (g cm-3)',	'method',	'Fine earth (estimated coarse fraction correction) bulk density',
'ISCN3',	'layer',	'bd_other (g cm-3)',	'description',	'Grams of oven-dried soil per cubic centimeter, method used in the associated Bulk Density Method, soil particle fraction used',
'ISCN3',	'layer',	'bd_other (g cm-3)',	'unit',	'g cm-3',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'description',	'NRCS bulk density method code',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'control_vocabulary',	'NRCS_bulk_density_code')

ISCN.dataStructure <- tribble(~'study_id', ~'table_id', ~'column_id', ~'is_type', ~'of_variable',
  'ISCN3',	'layer',	'bd_method',	'method',	'bulk_density_sample',
  'ISCN3',	'layer',	'bd_method',	'method',	'bulk_density_total',
  'ISCN3',	'layer',	'bd_method',	'method',	'bulk_density_whole',
  'ISCN3',	'layer',	'bd_method',	'method',	'bulk_density_other',
'ISCN3',	'layer',	'bd_samp (g cm-3)',	'value',	'bulk_density_sample',
'ISCN3',	'layer',	'bd_tot (g cm-3)',	'value',	'bulk_density_total',
'ISCN3',	'layer',	'bd_whole (g cm-3)',	'value',	'bulk_density_whole',
'ISCN3',	'layer',	'bd_other (g cm-3)',	'value',	'bulk_density_other',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'method',	'bulk_density_sample',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'method',	'bulk_density_total',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'method',	'bulk_density_whole',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'method',	'bulk_density_other'
)

fullMeta <- ISCN.dataStructure  %>% select(-is_type) %>%
  full_join(ISCN.dataDescription, multiple = 'all') %>%
  full_join(ISCN.df %>%
              mutate(study_id = 'ISCN3', table_id = 'layer') %>%
              pivot_longer(cols = ISCN.dataDescription$column_id, names_to = 'column_id', 
                           values_to = 'with_entry', values_drop_na = TRUE)%>% 
              select(study_id, table_id, column_id, 
                     dataset_name_sub, site_name, profile_name, layer_name) %>%
              unique())

ISCN_long.df <- ISCN.df %>%
  mutate(study_id = 'ISCN3', table_id = 'layer')  %>%
  pivot_longer(cols = ISCN.dataDescription$column_id, names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  #workflow 1
  left_join(ISCN.dataStructure, by = join_by(study_id, table_id, column_id), multiple = 'all') %>%
  bind_rows(fullMeta) %>%
  select(-column_id) %>%
  ##pull out the tuple
  pivot_wider(names_from=is_type, values_from='with_entry', values_fn = function(...) paste(..., sep = ',', collapse = ';')) %>%
  filter(!is.na(value))
  
   

ISCN_long.df <- ISCN.df %>%
  mutate(study_id = 'ISCN3', table_id = 'layer')  %>%
  pivot_longer(cols = ISCN.dataDescription$column_id, names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  #work flow 2
  left_join(ISCN.dataStructure, 
            by = join_by(study_id, table_id, column_id), multiple = 'all') %>%
  left_join(ISCN.dataDescription, 
            by = join_by(study_id, table_id, column_id),
            suffix = c('.data', '.meta'), multiple = 'all') %>%
  reframe(
    with_entry = c(with_entry.meta, with_entry.data),
    is_type = c(is_type.meta, is_type.data),
    .by = c(dataset_name_sub, site_name, profile_name, layer_name, 
           study_id, table_id, of_variable)
  ) %>%
  unique() %>%
  ##pull out the tuple
  pivot_wider(names_from=is_type, 
              values_from='with_entry', 
              values_fn = function(...) paste(..., sep = ',', collapse = ';')) %>%
  filter(!is.na(value))



```

# Adding Identifying Columns


```{r}

#Transform the data into a set of id-variable-value-unit-method 

FIA.dataStructure <- tribble(~'study_id', ~'table_id', ~'column_id', ~'is_type', ~of_variable,
  'FIADB_RMRS', 'Soils_Lab', 'BULK_DENSITY', 'value', 'Bulk_density',
  'FIADB_RMRS', 'Soils_Lab', 'CN', 'identifier', 'code', 
 'FIADB_RMRS', 'Soils_Lab', 'STATECD', 'identifier', 'state', 
 'FIADB_RMRS', 'Soils_Lab', 'COUNTYCD', 'identifier', 'county', 
 'FIADB_RMRS', 'Soils_Lab', 'PLOT', 'identifier', 'plot', 
 'FIADB_RMRS', 'Soils_Lab', 'SMPLNNBR', 'identifier', 'sample_number', 
 'FIADB_RMRS', 'Soils_Lab', 'VSTNBR', 'identifier', 'station_number'
)

FIA.dataDescription <- tribble(~'study_id', ~'table_id', ~'column_id', ~'is_type', ~'with_entry',
         'FIADB_RMRS', 'Soils_Lab',	'BULK_DENSITY', 'unit', 'g cm-3',
'FIADB_RMRS','Soils_Lab', 'BULK_DENSITY', 'method','mass per volume of oven-dry soil inclusive of coarse fraction') 


FIA_long.df <- FIA.df %>%
  mutate(study_id = 'FIADB_RMRS', 
         table_id = 'Soils_Lab',
         row_num = 1:n()) %>%
  pivot_longer(cols = any_of(FIA.dataStructure$column_id), names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  left_join(FIA.dataStructure, 
            by = join_by(study_id, table_id, column_id), multiple = 'all') %>%
  left_join(FIA.dataDescription, 
            by = join_by(study_id, table_id, column_id),
            suffix = c('.data', '.meta'), multiple = 'all') %>%
  reframe(
    with_entry =c(with_entry.meta, with_entry.data),
    is_type =  c(is_type.meta, is_type.data),
    .by = c(study_id, table_id, row_num, of_variable)
  ) %>%
  filter(!is.na(with_entry)) %>%
  unique() 
  
```

```{r}

ISCN.dataDescription <- tribble(~'study_id', ~'table_id', ~'column_id',~'is_type', ~'with_entry',
'ISCN3',	'layer',	'bd_method',	'description',	"Method used to determine bulk density",
'ISCN3',	'layer',	'bd_samp (g cm-3)',	'description',	'Grams of oven-dried soil per cubic centimeter, with soil particles greater than 2 mm and roots greater that 1 cm diameter removed',
'ISCN3',	'layer',	'bd_samp (g cm-3)',	'unit',	'g cm-3',
'ISCN3',	'layer',	'bd_samp (g cm-3)',	'method',	'Fine earth bulk density',
'ISCN3',	'layer',	'bd_tot (g cm-3)',	'description',	'Grams of oven-dried soil per cubic centimeter, with soil particles greater than 2 mm and roots greater that 1 cm diameter included',
'ISCN3',	'layer',	'bd_tot (g cm-3)',	'unit',	'g cm-3',
'ISCN3',	'layer',	'bd_tot (g cm-3)',	'method',	'Whole soil bulk density',
'ISCN3',	'layer',	'bd_whole (g cm-3)',	'description',	'Grams of oven-dried soil per cubic centimeter, with the content of soil particles >2mm and roots >1cm diameter estimated and subtracted',
'ISCN3',	'layer',	'bd_whole (g cm-3)',	'unit',	'g cm-3',
'ISCN3',	'layer',	'bd_whole (g cm-3)',	'method',	'Fine earth (estimated coarse fraction correction) bulk density',
'ISCN3',	'layer',	'bd_other (g cm-3)',	'description',	'Grams of oven-dried soil per cubic centimeter, method used in the associated Bulk Density Method, soil particle fraction used',
'ISCN3',	'layer',	'bd_other (g cm-3)',	'unit',	'g cm-3',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'description',	'NRCS bulk density method code',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'control_vocabulary',	'NRCS_bulk_density_code')

ISCN.dataStructure <- tribble(~'study_id', ~'table_id', ~'column_id', ~'is_type', ~'of_variable',
  'ISCN3',	'layer',	'bd_method',	'method',	'bulk_density_sample',
  'ISCN3',	'layer',	'bd_method',	'method',	'bulk_density_total',
  'ISCN3',	'layer',	'bd_method',	'method',	'bulk_density_whole',
  'ISCN3',	'layer',	'bd_method',	'method',	'bulk_density_other',
'ISCN3',	'layer',	'bd_samp (g cm-3)',	'value',	'bulk_density_sample',
'ISCN3',	'layer',	'bd_tot (g cm-3)',	'value',	'bulk_density_total',
'ISCN3',	'layer',	'bd_whole (g cm-3)',	'value',	'bulk_density_whole',
'ISCN3',	'layer',	'bd_other (g cm-3)',	'value',	'bulk_density_other',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'method',	'bulk_density_sample',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'method',	'bulk_density_total',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'method',	'bulk_density_whole',
'ISCN3',	'layer',	'bdNRCS_prep_code',	'method',	'bulk_density_other',
'ISCN3', 'layer',	'dataset_name_sub',	'identifier',	'data_source',
'ISCN3',	'layer',	'dataset_name_soc',	'identifier',	'soil_organic_carbon',
'ISCN3',	'layer',	'site_name',	'identifier',	'site',
'ISCN3',	'layer',	'profile_name',	'identifier',	'profile',
'ISCN3',	'layer',	'layer_name',	'identifier',	'layer'
)


ISCN_long.df <- ISCN.df %>%
  mutate(study_id = 'ISCN3',
         table_id = 'layer',
         row_num = 1:n())  %>%
  pivot_longer(cols = any_of(ISCN.dataStructure$column_id), names_to = 'column_id', 
               values_to = 'with_entry', values_drop_na = TRUE) %>%
  left_join(ISCN.dataStructure, 
            by = join_by(study_id, table_id, column_id), multiple = 'all') %>%
  left_join(ISCN.dataDescription, 
            by = join_by(study_id, table_id, column_id),
            suffix = c('.data', '.meta'), multiple = 'all') %>%
  reframe(
    with_entry =c(with_entry.meta, with_entry.data),
    is_type =  c(is_type.meta, is_type.data),
    .by = c(study_id, table_id, row_num, of_variable)
  ) %>%
  filter(!is.na(with_entry)) %>%
  unique() 

ISCN_wide_values.df <- ISCN_long.df %>%
  filter(is_type %in% c('identifier', 'value')) %>%
  select(-is_type) %>%
  ##pull out the tuple
  pivot_wider(names_from=of_variable, 
              values_from=with_entry)



```

# Pulling things together: 

```{r}
bigData <- FIA_long.df %>%
  bind_rows(ISCN_long.df)

```

## Method 1: harmonizing data types

```{r}


newData.df <- bigData %>%
  mutate(of_variable = recode(of_variable, 
                           'Bulk_density' = 'bulk_density_whole'))

```

```{r}

#bigData %>%
#  select(study_id, table_id, of_variable, is_type, with_entry) %>%
#  filter(is_type %in% c('unit', 'method')) %>%
#  unique() %>% write.csv(row.names = FALSE)

variableMap <- tribble(~"study_id", ~"table_id", ~"of_variable", ~'target_variable', 
"FIADB_RMRS","Soils_Lab","Bulk_density", 'bulk_density_whole_soil',
"ISCN3","layer","bulk_density_sample", 'bulk_density_fine_earth',
"ISCN3","layer","bulk_density_other",'bulk_density_unknown',
"ISCN3","layer","bulk_density_total", 'bulk_density_whole_soil',
"ISCN3","layer","bulk_density_whole", 'bulk_density_whole_soil',
 "FIADB_RMRS", "Soils_Lab", "code", "code", 
 "FIADB_RMRS", "Soils_Lab", "state", "state", 
 "FIADB_RMRS", "Soils_Lab", "county", "county", 
 "FIADB_RMRS", "Soils_Lab", "plot", "plot", 
 "FIADB_RMRS", "Soils_Lab", "sample_number", "sample_number", 
 "FIADB_RMRS", "Soils_Lab", "station_number", "station_number", 
 "ISCN3", "layer", "data_source", "data_source", 
 "ISCN3", "layer", "site", "site", 
 "ISCN3", "layer", "profile", "profile", 
 "ISCN3", "layer", "layer", "layer", )

newData.df <- bigData %>%
  left_join(variableMap, by = join_by(study_id, table_id, of_variable)) %>%
  select(-of_variable) %>%
  rename(of_variable = target_variable)
  
```


# Plot it
```{r}

data_wide_values.df <- newData.df %>%
  filter(is_type %in% c('identifier', 'value')) %>%
  select(-is_type) %>%
  ##pull out the tuple
  pivot_wider(names_from=of_variable, 
              values_from=with_entry) %>%
  mutate(across(.cols = starts_with('bulk_density'), as.numeric))

meta_data <- newData.df %>%
  filter(!is_type %in% c('identifier', 'value')) %>%
  select(study_id, table_id, of_variable, is_type, with_entry) %>%
  unique()

ggplot(data_wide_values.df) +
  geom_histogram(aes(x=bulk_density_whole_soil)) +
  facet_wrap(~study_id, scales='free_y') +
  scale_x_log10()

ggplot(data_wide_values.df %>%
         pivot_longer(cols = c(bulk_density_whole_soil, bulk_density_fine_earth, bulk_density_unknown))) +
  geom_histogram(aes(x=value, fill = study_id)) +
  facet_grid(study_id~name, scales = 'free_y') +
  scale_x_log10() +
  scale_y_log10()

```
