# Oak Ridge National Lab_Loblolly_DWJ

ISCNv3 issues to resolve for ISCNv3.5

  Oak Ridge National Lab_Loblolly_DWJ
    + Country not set (clearly US)
    + cryptic site note in profile
    + hzn in layer and profile reset needs to be reset NA
    something analysis to NA needs to be switched to NA
    + gapfilled bd with resampling should be removed
   
    
```{r}
datasetName <- 'Oak Ridge National Lab_Loblolly_DWJ'

dataset_study <- citation_raw %>% 
  filter(dataset_name == datasetName) %>%
  select(where(function(xx){!(is.na(xx))})) %>%
  full_join( #putting citation and the dataset data together
    dataset_raw %>% 
              filter(dataset_name == datasetName) %>% #subset the dataset table
              select(where(function(xx){!(is.na(xx))})), suffix = c('_citation', '_dataset'))%>%
  standardCast()


#dataset_name_soc: Should this be changed to NA?
dataset_profile <- profile_raw  %>%
  filter(dataset_name_sub == datasetName) %>%
  mutate(`country (country)` = 'United States') %>%
  #how to I filter out data inside specific column
  standardCast() %>%
  filter(dataset_name_soc != 'ISCN SOC stock computation') #remove gapfilled values

dataset_layer <- layer_raw %>%
  filter(dataset_name_sub == datasetName) %>%
  standardCast() %>%
 mutate(`country (country)` = 'United States',
         `hzn` = case_when(
           hzn == "?" ~ "NA"
         ),
         `bd_tot (g cm-3)` = if_else(bd_method != 'gap-filled value from re-measurement of same plot in 2000', `bd_tot (g cm-3)`, NA_real_),
         `soc (g cm-2)` = if_else(dataset_name_soc != 'ISCN SOC stock computation', `soc (g cm-2)`, NA_real_),
         `soc_carbon_flag` = if_else(dataset_name_soc != 'ISCN SOC stock computation', `soc_carbon_flag`, NA_character_),
         `soc_method` = if_else(dataset_name_soc != 'ISCN SOC stock computation', `soc_method`, NA_character_)) %>%
  group_by(`dataset_name_sub`, `site_name`, `profile_name`, layer_name) %>%
  fill(starts_with('soc')) %>%
  filter(dataset_name_soc == 'ISCN SOC stock computation') %>%
 select(-dataset_name_soc)
  


#all_study <- bind_rows(dataset_study, all_study)
#all_profile <- bind_rows(dataset_profile, all_profile)
#all_layer <- bind_rows(dataset_layer, all_layer)
```

```{r}
dataset_study
summary(dataset_profile %>% select_if(is.factor))
summary(dataset_layer %>% select_if(is.factor))

ggplot(data =  map_data('state') %>%
         full_join(dataset_profile %>% 
                     mutate(region = 
                              tolower(`state (state_province)`), by = 'region') %>%
                     group_by(region) %>% 
                     tally)) + 
  geom_polygon(aes(x=long, y = lat, group=group, fill = n), 
               color = 'black') +
  coord_fixed(1.3) + 
  theme_nothing() 

ggplot(data =  map_data('state') %>% 
         filter(region %in% c("tennessee"))) + 
  geom_polygon(aes(x=long, y = lat, group = group), 
               fill = 'grey', color = 'black') + 
  geom_point(data=dataset_profile, 
             aes(x = `long (dec. deg)`, y = `lat (dec. deg)`),
             shape = 'x', color = 'red') +
  coord_fixed(1.3) +
  theme_nothing() 

dataset_layer %>%
  pivot_longer(cols = intersect(names(.), type_cols$num_cols), values_drop_na = TRUE) %>%
  group_by(name) %>% summarize(n = length(value), unique_n = length(unique(value))) %>%
  bind_rows(
    dataset_layer %>%
      pivot_longer(cols = intersect(names(.), type_cols$factor_cols), values_drop_na = TRUE) %>%
      group_by(name) %>% summarize(n = length(value), unique_n = length(unique(value))) ) %>%
  arrange(n) %>%
  knitr::kable()
##need to remove soc graph and lat long graphs
ggplot(dataset_layer %>% 
         pivot_longer( cols=c('layer_top (cm)', 'layer_bot (cm)'),
                       values_to='depth') %>%
         pivot_longer(cols = intersect(names(.), type_cols$num_cols), 
                      values_to = 'measurement', names_to = 'type')) +
         geom_line(aes(x=depth, y= measurement, group = profile_name)) +
  facet_wrap(~type, scales='free')
```