# Vogel

```{r warning=FALSE, message=FALSE}
datasetName <- 'Vogel'

##### Extract the study information ####
dataset_study <- citation_raw %>% 
  filter(dataset_name == datasetName) %>% #pull out the info on the dataset we want here
  select(where(function(xx){!all(is.na(xx))})) %>% #pull out columns where values are not all "NA"
  full_join( #put the citation and the dataset information together
    dataset_raw %>%
              filter(dataset_name == datasetName) %>% #subset the dataset table
              select(where(function(xx){!all(is.na(xx))})), #only pull columns that are not entirely NA values
    suffix = c('_citation', '_dataset'))%>% #flag common columns that are not the ID columns between the two tables
  standardCast() #go see index.Rmd for this function, mostly recasts the column to the right types

```

```{r warning=FALSE, message=FALSE}
##### Extract the profile information ####

dataset_profile <- profile_raw  %>%
  filter(dataset_name_sub == datasetName) %>% #pull out the info on the dataset we want here
  standardCast() %>% #recasting column to character type
  rename(dataset_name = 'dataset_name_sub') %>% #simplifying column name
  select(-dataset_name_soc, -starts_with('soc')) #removing ISCN flags that say nothing was done for the SOC fill

```

```{r warning=FALSE, message=FALSE}        
##### Extract the layer information ####

dataset_layer <- layer_raw %>%
  filter(dataset_name_sub == datasetName) %>% #pull out info for only this dataset
    standardCast() %>% 
  rename(dataset_name = 'dataset_name_sub') %>% #changing to more user-friendly name
  select(-dataset_name_soc, -starts_with('soc')) #removing ISCN flags that say nothing was done for the SOC fill

```




```{r message=FALSE, warning=FALSE}
knitr::kable(t(dataset_study))
```


There are the following factors in the profile:
```{r}
knitr::kable(summary(dataset_profile %>% select_if(is.factor)))
```

And the following factors in the layers:
```{r}
knitr::kable(summary(dataset_layer %>% select_if(is.factor)))
```


## Location

```{r}

##using location data to display what state/region of the United States was sampled
ggplot(data =  map_data('state') %>%  #identifying Alaska as state of interest in this data set
         full_join(dataset_profile %>% 
                     mutate(region = 
                              tolower(`state (state_province)`), by = 'region') %>%
                     group_by(region) %>% 
                     tally, by='region')) + #making state of interest a different color than the rest
  geom_polygon(aes(x=long, y = lat, group=group, fill = n), 
               color = 'black') + #making map outline black
  coord_fixed(1.3) + #fixing ratio  between y and x axes
  theme_nothing() + #prints map of U.S. with blank ggplot theme 
  labs(title = 'Profile data')

##using location data to plot sites on a state map
ggplot(data =  map_data('state') %>% #pull out relevant info, found in state column
         filter(region %in% c("alaska"))) + #selecting which states to include on second map
  geom_polygon(aes(x=long, y = lat, group = group), # creating the shape of the map; ‘group’ connects adjacent points with lines to outline shape
               fill = 'grey', color = 'black') +  
  geom_point(data=dataset_profile, #creating scatter plot of latitudes and longitudes from dataset_profile 
             aes(x = `long (dec. deg)`, y = `lat (dec. deg)`), #assigning latitude and longitude to respective axes
             shape = 'x', color = 'red') + #locations will be marked by red x
  coord_fixed(1.3) + #fixing ratio between y and x axes
  theme_nothing() + #prints select state map with site locations and blank ggplot theme
  labs(title = 'Layer data')
  
```







```{r}
#this is useful to see for the analysis but we don't want it in the report
#create a table that displays the names of the number and factor columns in the dataset, how many values there are in each, and how many unique values there are
dataset_layer %>% #pipe dataset_layer
  pivot_longer(cols = intersect(names(.), type_cols$num_cols), values_drop_na = TRUE) %>% #indicating what values will be used on plots and drop all NA values
  group_by(name) %>% summarize(n = length(value), unique_n = length(unique(value))) %>% #find how many total values and unique values each number column has
  bind_rows( #combine the number and factor column summaries into one dataframe
    dataset_layer %>% #pipe dataset_layer
      pivot_longer(cols = intersect(names(.), type_cols$factor_cols), values_drop_na = TRUE) %>% #indicating what values will be used on plots and drop all NA values
      group_by(name) %>% summarize(n = length(value), unique_n = length(unique(value))) ) %>% #find how many total values and unique values each factor column has
  arrange(n) %>%
  knitr::kable() #create the table
```

## Profile histograms

```{r}
##using profile data to create a histogram for each measured variable in this data set
ggplot(dataset_profile %>%
         pivot_longer(cols = intersect(names(.), type_cols$num_cols), #selecting what columns to pull
                      values_to = 'measurement', names_to = 'type')) + #naming x values and the variables to make histograms of
  geom_histogram(aes(x=measurement)) +  #setting x and y axes
  facet_wrap(~type, scales='free') +
  theme_bw() #using a compatible theme with histogram function
```

## Depth plots

```{r}
##using layer data to create a plot for each measured variable at corresponding depths in this data set
ggplot(dataset_layer %>% 
         pivot_longer( cols=c('layer_top (cm)', 'layer_bot (cm)'),
                       values_to='depth') %>% 
         pivot_longer(cols = intersect(names(.), type_cols$num_cols), 
                      values_to = 'measurement', names_to = 'type')) + #indicating what values will be used on plots
         geom_line(aes(x=depth, y= measurement, group = profile_name), alpha = 0.5) + #assigning which sets of values will be on x and y axes
  facet_wrap(~type, scales='free') +
  theme_bw()
```
